# Generated by Django 2.2.1 on 2019-05-27 00:27

from django.db import migrations
from product_scraper.db_helper import populate_product_db

class Migration(migrations.Migration):

    dependencies = [
        ('product_scraper', '0002_auto_20190523_2026'),
    ]

    operations = [
        migrations.RunPython(populate_product_db())
    ]
