# Generated by Django 2.2.1 on 2019-05-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_scraper', '0002_auto_20190523_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Product',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
