# Generated by Django 2.2.1 on 2019-05-28 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_scraper', '0003_auto_20190526_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
    ]
